import { createSlice } from "@reduxjs/toolkit";
import type { PayloadAction } from "@reduxjs/toolkit";

// Define the Post interface based on your backend schema
export interface Post {
  _id: string;
  description: string;
  image?: string;
  user: any;
  likes: string[];
  comments: any[];
  createdAt?: string;
  updatedAt?: string;
}

// Define the PostState interface
interface PostState {
  posts: Post[];
  currentPost: Post | null;
  isLoading: boolean;
  error: string | null;
  page: number;
  hasMore: boolean;
}
// Define the initial statefor the post slice
const initialState: PostState = {
  posts: [],
  currentPost: null,
  isLoading: false,
  error: null,
  page: 1,
  hasMore: true,
};

// Create the post slice using createSlice from Redux Toolkit
const postSlice = createSlice({
  name: "posts",
  initialState,
  reducers: {
//set the list of posts (e.g., when fetching from the server)
    setPosts: (state, action: PayloadAction<Post[]>) => {
      state.posts = action.payload;
    },

    appendPosts: (state, action: PayloadAction<Post[]>) => {
      state.posts = [...state.posts, ...action.payload];
    },

    addPost: (state, action: PayloadAction<Post>) => {
      state.posts.unshift(action.payload);
    },

    updatePost: (state, action: PayloadAction<Post>) => {
      const index = state.posts.findIndex(
        (p) => p._id === action.payload._id
      );

      if (index !== -1) {
        state.posts[index] = action.payload;
      }
    },

    removePost: (state, action: PayloadAction<string>) => {
      state.posts = state.posts.filter(
        (p) => p._id !== action.payload
      );
    },

    setCurrentPost: (
      state,
      action: PayloadAction<Post | null>
    ) => {
      state.currentPost = action.payload;
    },

    //ui state management reducers
    setLoading: (state, action: PayloadAction<boolean>) => {
      state.isLoading = action.payload;
    },

    setError: (
      state,
      action: PayloadAction<string | null>
    ) => {
      state.error = action.payload;
    },

    setPage: (state, action: PayloadAction<number>) => {
      state.page = action.payload;
    },

    setHasMore: (
      state,
      action: PayloadAction<boolean>
    ) => {
      state.hasMore = action.payload;
    },

    //reset the post state to initial (e.g., on logout or when leaving the posts page)
    resetPostsState: () => initialState,
  },
});

// Export the actions generated by createSlice
export const {
  setPosts,
  appendPosts,
  addPost,
  updatePost,
  removePost,
  setCurrentPost,
  setLoading,
  setError,
  setPage,
  setHasMore,
  resetPostsState,
} = postSlice.actions;
// Export the reducer to be used in the store
export default postSlice.reducer;